### ISSUE TITLE
Close button not appearing when article opens

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-article-reveal#16]
Testing this extension and I am not seeing any Close button appearing once I open the article.

If I inspect the code I can see the close button is set to display:none;

**Comment by moloko** [comment]
yep see what you mean... in our defence this extension is rarely used 'out of the box' as every learning designer seems to have a different take on how it is supposed to work - so we find we have to customise it every time anyway!

however since I have a requirement on a project for this extension to have the close functionality I'll see about adding that back in here (perhaps with an 'allow closing' config option)

**Comment by moloko** [comment]
@paul-mediakitchen done - see #19
